language: java
sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.gradle

script:
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ "[release]" ]]; then ./gradlew build; println '>>SNAPSHOT<<' ; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == "[release]" ]]; then ./gradlew build release; println '>>RELEASE<<' ; fi ;

after_success:
  - if [[ $TRAVIS_COMMIT_MESSAGE == "[release]" ]]; then ./gradlew release; println '>>MAJOR RELEASE<<' ; fi ;
