language: java
sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.gradle

script:
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[major release]"* ]]; then println '>>MAJOR RELEASE<<' ; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[minor release]"* ]]; then println '>>MINOR RELEASE<<' ; fi ;
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[patch release]"* ]]; then println '>>PATCH RELEASE<<' ; fi ;
  - ./gradlew build

after_success:
  - println '>>SUCCESS!<<'



